# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core sdk 3.0.100-preview7-012821'
  inputs:
    version: 3.0.100-preview7-012821
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- script: dotnet pack --configuration $(buildConfiguration) --version-suffix "ci-$(Build.BuildId)" -o $(Build.ArtifactStagingDirectory)
  displayName: 'dotnet pack $(buildConfiguration)'

- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    nuGetFeedType: 'internal'
    publishVstsFeed: '30604525-beb7-4eda-87a5-d7581086e7f7/8cb5ed78-47d8-4c0b-b1eb-ad0fbf33bea0'
    allowPackageConflicts: true
