// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AndriiKurdiumov.SportRadar.Client.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PeriodScore
    {
        /// <summary>
        /// Initializes a new instance of the PeriodScore class.
        /// </summary>
        public PeriodScore()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PeriodScore class.
        /// </summary>
        public PeriodScore(int number, string type, int homeScore, int awayScore)
        {
            Number = number;
            Type = type;
            HomeScore = homeScore;
            AwayScore = awayScore;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "number")]
        public int Number { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "home_score")]
        public int HomeScore { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "away_score")]
        public int AwayScore { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Type == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Type");
            }
        }
    }
}
