// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AndriiKurdiumov.SportRadar.Client.Models
{
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Season
    {
        /// <summary>
        /// Initializes a new instance of the Season class.
        /// </summary>
        public Season()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Season class.
        /// </summary>
        public Season(string id, string name, System.DateTime startDate, System.DateTime endDate, string year, string tournamentId)
        {
            Id = id;
            Name = name;
            StartDate = startDate;
            EndDate = endDate;
            Year = year;
            TournamentId = tournamentId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonConverter(typeof(DateJsonConverter))]
        [JsonProperty(PropertyName = "start_date")]
        public System.DateTime StartDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonConverter(typeof(DateJsonConverter))]
        [JsonProperty(PropertyName = "end_date")]
        public System.DateTime EndDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "year")]
        public string Year { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tournament_id")]
        public string TournamentId { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Id == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Id");
            }
            if (Name == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Name");
            }
            if (Year == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Year");
            }
            if (TournamentId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "TournamentId");
            }
        }
    }
}
