// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AndriiKurdiumov.SportRadar.Client
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for SportRadarSoccerAPI.
    /// </summary>
    public static partial class SportRadarSoccerAPIExtensions
    {
            /// <summary>
            /// Get daily results
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='accessLevel'>
            /// Possible values include: 'x', 't'
            /// </param>
            /// <param name='leagueGroup'>
            /// Possible values include: 'eu', 'intl', 'am', 'as', 'global', 'other'
            /// </param>
            /// <param name='languageCode'>
            /// </param>
            /// <param name='year'>
            /// The calendar year
            /// </param>
            /// <param name='month'>
            /// The calendar month
            /// </param>
            /// <param name='day'>
            /// The calendar day
            /// </param>
            public static DailyResults GetDailyResults(this ISportRadarSoccerAPI operations, string accessLevel, string leagueGroup, string languageCode, int year, int month, int day)
            {
                return operations.GetDailyResultsAsync(accessLevel, leagueGroup, languageCode, year, month, day).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get daily results
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='accessLevel'>
            /// Possible values include: 'x', 't'
            /// </param>
            /// <param name='leagueGroup'>
            /// Possible values include: 'eu', 'intl', 'am', 'as', 'global', 'other'
            /// </param>
            /// <param name='languageCode'>
            /// </param>
            /// <param name='year'>
            /// The calendar year
            /// </param>
            /// <param name='month'>
            /// The calendar month
            /// </param>
            /// <param name='day'>
            /// The calendar day
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<DailyResults> GetDailyResultsAsync(this ISportRadarSoccerAPI operations, string accessLevel, string leagueGroup, string languageCode, int year, int month, int day, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetDailyResultsWithHttpMessagesAsync(accessLevel, leagueGroup, languageCode, year, month, day, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
